server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost/blog
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp